# Generated by Django 4.0.4 on 2022-05-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ginasio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='altura',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='idade',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='peso',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
