# Generated by Django 4.0.4 on 2022-05-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ginasio', '0002_alter_profile_altura_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='especialidade',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
