# Generated by Django 4.0.4 on 2022-05-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ginasio', '0003_profile_especialidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='objetivo',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='especialidade',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
