# Generated by Django 4.0.4 on 2022-05-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ginasio', '0004_profile_objetivo_alter_profile_especialidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='displayclients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
